spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profiles: local
  datasource:
    hikari:
      jdbc-url:
      username: sa
      password:
      driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3309/springbatch?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hibernate.format_sql: true
  batch:
    job:
      names: ${job.name:NONE}
      enabled: true
    jdbc:
      initialize-schema: always